[project]
name = 'Quantum-Realm-Mining-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.entanglement-difficulty-adjustment]
path = 'contracts/entanglement-difficulty-adjustment.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-fluctuation-harnessing]
path = 'contracts/quantum-fluctuation-harnessing.clar'
clarity_version = 2
epoch = 2.5

[contracts.uncertainty-reward-distribution]
path = 'contracts/uncertainty-reward-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
